export const UNIVERSITY_CATALOG = [
  'University of Colombo',
  'University of Peradeniya',
  'University of Sri Jayewardenepura',
  'University of Kelaniya',
  'University of Moratuwa',
  'University of Jaffna',
  'University of Ruhuna',
  'Open University of Sri Lanka',
  'Eastern University, Sri Lanka',
  'Rajarata University of Sri Lanka',
  'Wayamba University of Sri Lanka',
  'Sabaragamuwa University of Sri Lanka',
  'South Eastern University of Sri Lanka',
  'Uva Wellassa University',
  'University of the Visual & Performing Arts',
  'Gampaha Wickramarachchi University of Indigenous Medicine',
  'University of Vavuniya',
  'General Sir John Kotelawala Defence University (KDU)',
  'Ocean University of Sri Lanka (OCU)',
  'University of Vocational Technology (UNIVOTEC)',
  'Buddhist and Pali University of Sri Lanka',
  'Bhiksu University of Sri Lanka',
  'National Institute of Social Development (NISD)',
  'Sri Lanka Institute of Information Technology (SLIIT)',
  'National School of Business Management (NSBM)',
  'National Institute of Business Management (NIBM)',
  'Horizon Campus',
  'KAATSU International University (KIU)',
  'Colombo International Nautical and Engineering College (CINEC)',
  'Aquinas College of Higher Studies',
  'Sliit City Uni',
  'Saegis Campus',
  'SANASA Campus',
  'International College of Business and Technology (ICBT)',
  'Gateway Graduate School',
  'Nagananda International Institute for Buddhist Studies (NIIBS)',
  'Sri Lanka Institute of Marketing (SLIM)',
  'Institute of Chartered Accountants of Sri Lanka (CA Sri Lanka)',
  'Institute of Bankers of Sri Lanka (IBSL)',
] as const;
